[package]
name = "site"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
from-pest = "0.3.2"
pest = "2.7.13"
pest_derive = "2.7.13"
trql = { version = "0.2.1", path = "../trql" }
jsonxf = "1.1.1"
