name: Publish

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Setup Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cargo/bin/cargo-workspaces
          key: ${{ runner.os }}-cargo-workspaces
      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
      - name: Publish All Packages
        run: cargo workspaces publish --from-git --yes --no-verify
